version: "3.8"
services:
  booking:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/booking/
    working_dir: /var/www/html/booking/
  booking-database:
    image: mysql:8.0.23
    restart: unless-stopped
    volumes:
      - booking-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
volumes:
  booking-database:
